### ISSUE TITLE
minimal-ros-install script fails in last few lines

### ISSUE THREAD

**Issue by JetForMe** [vmayoral/beagle-ros#3]
The last few lines fail:

Setting up the environment...
cat: passwd: No such file or directory
cat: bashrc: No such file or directory

Not sure where it's trying to find those files, or what the desired effect is.

**Comment by JetForMe** [comment]
This is on Angstrom 2013/9/4

**Comment by vmayoral** [comment]
@JetForMe that's probably being caused because you're running [minimal-ros-install-angstrom.sh](https://github.com/vmayoral/beagle-ros/blob/master/scripts/minimal-ros-install-angstrom.sh) from somewhere [else](https://github.com/vmayoral/beagle-ros#getting-roscore-running). Those [lines](https://github.com/vmayoral/beagle-ros/blob/master/scripts/minimal-ros-install-angstrom.sh#L56) in the script configure the environment.

Make sure that at least you [configure your environment](https://github.com/vmayoral/beagle-ros/blob/master/scripts/bashrc) properly.

Regards,

**Comment by JetForMe** [comment]
Actually, I think it may be because I tried to run the script directly, rather than executing the git instruction first? I didn't realize the three lines in the page resulted in the script being downloaded and executed.

**Comment by JetForMe** [comment]
Yeah, that was it.
